from BaseClasses import Location
import typing

from worlds.apeescape.Strings import AELocation

base_location_id = 128000000


class ApeEscapeLocation(Location):
    game: str = "Ape Escape"

    def __init__(self, player: int, name: str, address: typing.Optional[int], parent):
        super().__init__(player, name, address, parent)
        self.event = not address

location_table = {
    #1-1 Fossil Field
    AELocation.Noonan.value: 1,
    AELocation.Jorjy.value: 2,
    AELocation.Nati.value: 3,
    AELocation.TrayC.value: 4,
    #1-2 Primordial Ooze
    AELocation.Shay.value: 5,
    AELocation.DrMonk.value: 6,
    AELocation.Grunt.value: 7,
    AELocation.Ahchoo.value: 8,
    AELocation.Gornif.value: 9,
    AELocation.Tyrone.value: 10,
    #1-3 Molten Lava
    AELocation.Scotty.value: 11,
    AELocation.Coco.value: 12,
    AELocation.JThomas.value: 13,
    AELocation.Mattie.value: 14,
    AELocation.Barney.value: 15,
    AELocation.Rocky.value: 16,
    AELocation.Moggan.value: 17,
    #2-1 Thick Jungle
    AELocation.Marquez.value: 18,
    AELocation.Livinston.value: 19,
    AELocation.George.value: 20,
    AELocation.Maki.value: 21,
    AELocation.Herb.value: 22,
    AELocation.Dilweed.value: 23,
    AELocation.Mitong.value: 24,
    AELocation.Stoddy.value: 25,
    AELocation.Nasus.value: 26,
    AELocation.Selur.value: 27,
    AELocation.Elehcim.value: 28,
    AELocation.Gonzo.value: 29,
    AELocation.Alphonse.value: 30,
    AELocation.Zanzibar.value: 31,
    #2-2 Dark Ruins
    AELocation.Mooshy.value: 32,
    AELocation.Kyle.value: 33,
    AELocation.Cratman.value: 34,
    AELocation.Nuzzy.value: 35,
    AELocation.Mav.value: 36,
    AELocation.Stan.value: 37,
    AELocation.Bernt.value: 38,
    AELocation.Runt.value: 39,
    AELocation.Hoolah.value: 40,
    AELocation.Papou.value: 41,
    AELocation.Kenny.value: 42,
    AELocation.Trance.value: 43,
    AELocation.Chino.value: 44,
    #2-3 Cryptic Relics
    AELocation.Troopa.value: 45,
    AELocation.Spanky.value: 46,
    AELocation.Stymie.value: 47,
    AELocation.Pally.value: 48,
    AELocation.Freeto.value: 49,
    AELocation.Jesta.value: 50,
    AELocation.Bazzle.value: 51,
    AELocation.Crash.value: 52,
    #4-1 Crabby Beach
    AELocation.CoolBlue.value: 53,
    AELocation.Sandy.value: 54,
    AELocation.ShellE.value: 55,
    AELocation.Gidget.value: 56,
    AELocation.Shaka.value: 57,
    AELocation.MaxMahalo.value: 58,
    AELocation.Moko.value: 59,
    AELocation.Puka.value: 60,
    #4-2 Coral Cave
    AELocation.Chip.value: 61,
    AELocation.Oreo.value: 62,
    AELocation.Puddles.value: 63,
    AELocation.Kalama.value: 64,
    AELocation.Iz.value: 65,
    AELocation.Jux.value: 66,
    AELocation.BongBong.value: 67,
    AELocation.Pickles.value: 68,
    #4-3 Dexter's Island
    AELocation.Stuw.value: 69,
    AELocation.TonTon.value: 70,
    AELocation.Murky.value: 71,
    AELocation.Howeerd.value: 72,
    AELocation.Robbin.value: 73,
    AELocation.Jakkee.value: 74,
    AELocation.Frederic.value: 75,
    AELocation.Baba.value: 76,
    AELocation.Mars.value: 77,
    AELocation.Horke.value: 78,
    AELocation.Quirck.value: 79,
    #5-1 Snowy Mammoth
    AELocation.Popcicle.value: 80,
    AELocation.Iced.value: 81,
    AELocation.Denggoy.value: 82,
    AELocation.Skeens.value: 83,
    AELocation.Rickets.value: 84,
    AELocation.Chilly.value: 85,
    #5-2 Frosty Retreat
    AELocation.Storm.value: 86,
    AELocation.Qube.value: 87,
    AELocation.Gash.value: 88,
    AELocation.Kundra.value: 89,
    AELocation.Shadow.value: 90,
    AELocation.Ranix.value: 91,
    AELocation.Sticky.value: 92,
    AELocation.Sharpe.value: 93,
    AELocation.Droog.value: 94,
    #5-3 Hot Springs
    AELocation.Punky.value: 95,
    AELocation.Ameego.value: 96,
    AELocation.Roti.value: 97,
    AELocation.Dissa.value: 98,
    AELocation.Yoky.value: 99,
    AELocation.Jory.value: 100,
    AELocation.Crank.value: 101,
    AELocation.Claxter.value: 102,
    AELocation.Looza.value: 103,
    #7-1 Sushi Temple
    AELocation.Taku.value: 104,
    AELocation.Rocka.value: 105,
    AELocation.Maralea.value: 106,
    AELocation.Wog.value: 107,
    AELocation.Long.value: 108,
    AELocation.Mayi.value: 109,
    AELocation.Owyang.value: 110,
    AELocation.QuelTin.value: 111,
    AELocation.Phaldo.value: 112,
    AELocation.Voti.value: 113,
    AELocation.Elly.value: 114,
    AELocation.Chunky.value: 115,
    #7-2 Wabi Sabi Wall
    AELocation.Minky.value: 116,
    AELocation.Zobbro.value: 117,
    AELocation.Xeeto.value: 118,
    AELocation.Moops.value: 119,
    AELocation.Zanabi.value: 120,
    AELocation.Buddha.value: 121,
    AELocation.Fooey.value: 122,
    AELocation.Doxs.value: 123,
    AELocation.Kong.value: 124,
    AELocation.Phool.value: 125,
    #7-3 Crumbling Castle
    AELocation.Naners.value: 126,
    AELocation.Robart.value: 127,
    AELocation.Neeners.value: 128,
    AELocation.Gustav.value: 129,
    AELocation.Wilhelm.value: 130,
    AELocation.Emmanuel.value: 131,
    AELocation.SirCutty.value: 132,
    AELocation.Calligan.value: 133,
    AELocation.Castalist.value: 134,
    AELocation.Deveneom.value: 135,
    AELocation.Igor.value: 136,
    AELocation.Charles.value: 137,
    AELocation.Astur.value: 138,
    AELocation.Kilserack.value: 139,
    AELocation.Ringo.value: 140,
    AELocation.Densil.value: 141,
    AELocation.Figero.value: 142,
    AELocation.Fej.value: 143,
    AELocation.Joey.value: 144,
    AELocation.Donqui.value: 145,
    #8-1 City Park
    AELocation.Kaine.value: 146,
    AELocation.Jaxx.value: 147,
    AELocation.Gehry.value: 148,
    AELocation.Alcatraz.value: 149,
    AELocation.Tino.value: 150,
    AELocation.QBee.value: 151,
    AELocation.McManic.value: 152,
    AELocation.Dywan.value: 153,
    AELocation.CKHutch.value: 154,
    AELocation.Winky.value: 155,
    AELocation.BLuv.value: 156,
    AELocation.Camper.value: 157,
    AELocation.Huener.value: 158,
    #8-2 Specter's Factory
    AELocation.BigShow.value: 159,
    AELocation.Dreos.value: 160,
    AELocation.Reznor.value: 161,
    AELocation.Urkel.value: 162,
    AELocation.VanillaS.value: 163,
    AELocation.Radd.value: 164,
    AELocation.Shimbo.value: 165,
    AELocation.Hurt.value: 166,
    AELocation.String.value: 167,
    AELocation.Khamo.value: 168,
    #8-3 TV Tower
    AELocation.Fredo.value: 169,
    AELocation.Charlee.value: 170,
    AELocation.Mach3.value: 171,
    AELocation.Tortuss.value: 172,
    AELocation.Manic.value: 173,
    AELocation.Ruptdis.value: 174,
    AELocation.Eighty7.value: 175,
    AELocation.Danio.value: 176,
    AELocation.Roosta.value: 177,
    AELocation.Tellis.value: 178,
    AELocation.Whack.value: 179,
    AELocation.Frostee.value: 180,
    #9-1 Monkey Madness
    AELocation.Goopo.value: 181,
    AELocation.Porto.value: 182,
    AELocation.Slam.value: 183,
    AELocation.Junk.value: 184,
    AELocation.Crib.value: 185,
    AELocation.Nak.value: 186,
    AELocation.Cloy.value: 187,
    AELocation.Shaw.value: 188,
    AELocation.Flea.value: 189,
    AELocation.Schafette.value: 190,
    AELocation.Donovan.value: 191,
    AELocation.Laura.value: 192,
    AELocation.Uribe.value: 193,
    AELocation.Gordo.value: 194,
    AELocation.Raeski.value: 195,
    AELocation.Poopie.value: 196,
    AELocation.Teacup.value: 197,
    AELocation.Shine.value: 198,
    AELocation.Wrench.value: 199,
    AELocation.Bronson.value: 200,
    AELocation.Bungee.value: 201,
    AELocation.Carro.value: 202,
    AELocation.Carlito.value: 203,
    AELocation.BG.value: 204,
    AELocation.Specter.value: 205
}
