from enum import Enum
import typing

class AELocation(Enum):
    Noonan = "1-1 Fossil Field Monkey 1 - Noonan"
    Jorjy = "1-1 Fossil Field Monkey 2 - Jorjy"
    Nati = "1-1 Fossil Field Monkey 3 - Nati"
    TrayC = "1-1 Fossil Field Monkey 4 - Tray C"
    Shay = "1-2 Primordial Ooze Monkey 1 - Shay"
    DrMonk = "1-2 Primordial Ooze Monkey 2 - Dr. Monk"
    Grunt = "1-2 Primordial Ooze Monkey 3 - Grunt"
    Ahchoo = "1-2 Primordial Ooze Monkey 4 - Ah-choo"
    Gornif = "1-2 Primordial Ooze Monkey 5 - Gornif"
    Tyrone = "1-2 Primordial Ooze Monkey 6 - Tyrone"
    Scotty = "1-3 Molten Lava Monkey 1 - Scotty"
    Coco = "1-3 Molten Lava Monkey 2 - Coco"
    JThomas = "1-3 Molten Lava Monkey 3 - J. Thomas"
    Mattie = "1-3 Molten Lava Monkey 4 - Mattie"
    Barney = "1-3 Molten Lava Monkey 5 - Barney"
    Rocky = "1-3 Molten Lava Monkey 6 - Rocky"
    Moggan = "1-3 Molten Lava Monkey 7 - Moggan"

class AERoom(Enum):
    W1L1Main = "1-1 Main"
    W1L1MainTrayC = "1-1 Main Tray C"
    W1L2Main = "1-2 Main"
    W1L2MainGrunt = "1-2 Main Grunt"
    W1L2MainGornif = "1-2 Main Gornif"
    W1L3Entry = "1-3 Entry"
    W1l3Volcano = "1-3 Volcano"
    W1L3Triceratops = "1-3 Triceratops Room"

class AEWorld(Enum):
    W1 = "World 1"
    W2 = "World 2"
    W3 = "World 3"
    W4 = "World 4"
    W5 = "World 5"
    W6 = "World 6"
    W7 = "World 7"
    W8 = "World 8"
    W9 = "World 9"

class AEItem(Enum):
    Club = "Stun Club"
    Net = "Time Net"
    Radar = "Monkey Radar"
    Sling = "Slingback Shooter"
    Hoop = "Super Hoop"
    Punch = "Magic Punch"
    Flyer = "Sky Flyer"
    Car = "R.C. Car"
    Key = "World Key"
    Victory = "Victory"
    Nothing = "Nothing"
    WaterNet = "Water Net"